name: deploy-to-staging
on:
  push:
    branches:
      # When someone push to `master` branch
      - master

jobs:
  pre-commit_and_test:
    uses: ./.github/workflows/ci.yml
  deploy:
    concurrency:
      group: ${{ github.ref }}
    needs: pre-commit_and_test
    name: "Deploy to staging"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Pull the latest code to the staging environment
        run: ssh staging 'cd saas-erp && git pull origin'

      - name: Start containers
        run: |
          ssh staging 'cd saas-erp && && bash scripts/start_server.sh'

      - name: Test the App
        run: |
          ssh staging 'if [ $( docker ps -a | grep saas-erp | wc -l ) -gt 0 ]; then  echo "saas-erp exists"; else   echo "saas-erp does not exist" && raise error; fi'
